@url = http://localhost:3000

GET {{url}}/employees/
###

GET {{url}}/employees/2edab739af0bd341b44c
###

POST {{url}}/employees
Content-Type: application/json

{
  "name": "Joe",
  "position": "Manager",
  "salary": 100000
}
###

GET {{url}}/reports/salaries
###
