@url = http://localhost:3000

GET {{url}}/employees/
###

GET {{url}}/employees/2edab739af0bd341b44c
###

POST {{url}}/employees
Content-Type: application/json

{
  "name": "Mike",
  "position": "Engineer",
  "salary": 100000,
  "other": "stuff"
}